### ISSUE TITLE
Scarthgap support?

### ISSUE THREAD

**Issue by om26er** [Xilinx/meta-som#2]
Whats the plan for scarthgap support. I am porting our distribution to Kira KR260 board and it looks like scarthgap is not supported by these recipes and apparently there hasn't been any activity on this repo for more than a year.

**Comment by chkohn** [comment]
@om26er we have this layer ported to scarthgap internally. Release testing is ongoing as we speak. Due to the holidays, I expect that the public release will happen early next year though.

**Comment by chkohn** [comment]
@om26er it seems like the release already happened, please check https://github.com/Xilinx/meta-kria/releases/tag/xlnx-rel-v2024.2_update1 

@mhatle let's get master updated please.

**Comment by om26er** [comment]
Awesome, thanks. I was looking for "scathgap" branch hence didnt find it. Thats usually the convention most yocto layers use.

**Comment by chkohn** [comment]
@om26er yes and we usually follow that. as scarthgap support for this layer was only released recently from our side, I assume @mhatle has not created or published the branch yet.

**Comment by mhatle** [comment]
We have scarthgap branches for meta-xilinx, meta-xilinx-tools and meta-amd-adaptive-socs.  At this point we've not created a specific branch for kria.   This is mostly because there are distribution related decisions that have been made in the meta-kria repository.  The way booting works, expectations of multiple device trees and daughter card handling and some petalinux dependencies (again distribution related.)

As chkohn indicated, the 2024.2 was scarthgap based and can be used.

**Comment by om26er** [comment]
@mhatle Is it possible to use this layer with Yocto without petalinux? We have a simple distribution based on scarthgap and want to add support for the Kria Kr260
